env:
  global:
    - xamarin_debug_logfile=xamarin-debug-log xamarin_debug_adapter_test_timeout=58000 ANDROID_COMPONENTS=build-tools-27.0.3,android-27,android-24,sys-img-armeabi-v7a-android-24 ANDROID_LICENSES=android-sdk-license-2742d1c5

matrix:
    include:
        - os: osx
          osx_image: xcode9.3
        - os: linux
          dist: xenial
          sudo: required

git:
  depth: 3

before_install:
  # install nodejs
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 6.5
  - nvm use 6.5
  # Install base Android SDK and components
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo apt-get install -qq libstdc++6:i386 lib32z1 expect; fi
  - source ./ci-scripts/install-android-sdk.sh
  - echo no | android -v create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off & #-verbose 
  # Install Xamarin
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./ci-scripts/macos-install-xamarin.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./ci-scripts/ubuntu-install-xamarin.sh; fi

install:
  - nuget restore mono-debug.sln
  - npm install

before_script:
  # Make sure the emulator has started before running tests
  - wait_for_emulator

script:
  - make build
  - npm test
