language: android

os:
  - osx

env:
  global:
    - ANDROID_COMPONENTS=build-tools-27.0.3,android-24,sys-img-armeabi-v7a-android-27
    - ANDROID_LICENSES=android-sdk-license-2742d1c5

git:
  submodules: false


before_install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 6.5
  - nvm use 6.5

install:
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$ANDROID_COMPONENTS --accept=$ANDROID_LICENSES
  - source ~/.android-sdk-installer/env
  - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - wait_for_emulator
  - wget "https://download.mono-project.com/archive/5.8.1/macos-10-universal/MonoFramework-MDK-5.8.1.0.macos10.xamarin.universal.pkg"
  - sudo installer -pkg "MonoFramework-MDK-5.8.1.0.macos10.xamarin.universal.pkg" -target /
  - wget "https://bosstoragemirror.azureedge.net/wrench/monodroid-mavericks-d15-6/a7/a7829590274ba0aad0e7d2d0dcbcb80d63c4b9e4/xamarin.android-8.2.0-16.pkg"
  - sudo installer -pkg "xamarin.android-8.2.0-16.pkg" -target /

  - nuget restore mono-debug.sln
  - npm install

script:
  - npm test
