language: android

os:
  - osx
  sudo: required
  
android:
  components:
    - tools
    - platform-tools

git:
  submodules: false


before_install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 6.5
  - nvm use 6.5

install:
  - wget "https://download.mono-project.com/archive/5.8.1/macos-10-universal/MonoFramework-MDK-5.8.1.0.macos10.xamarin.universal.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg" -target /
  - wget "https://bosstoragemirror.azureedge.net/wrench/monodroid-mavericks-d15-6/a7/a7829590274ba0aad0e7d2d0dcbcb80d63c4b9e4/xamarin.android-8.2.0-16.pkg"
  - sudo installer -pkg "xamarin.android-8.2.0-16.pkg" -target /

  - nuget restore mono-debug.sln
  - npm install

script:
  - npm test
